# Change these first
owner: ionburstcloud # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - jishf
sites:
  - name: Ionburst Cloud - eu-west-1
    url: https://api.eu-west-1.ionburst.cloud/web/check
    expectedStatusCodes:
      - 200
  - name: Ionburst Cloud - eu-west-2
    url: https://api.eu-west-2.ionburst.cloud/web/check
    expectedStatusCodes:
      - 200
  - name: Ionburst Cloud Portal
    url: https://portal.ionburst.cloud
    expectedStatusCodes:
      - 200
      - 302

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ionburst.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://status.ionburst.cloud/icon.svg
  themeUrl: https://status.ionburst.cloud/ibc.css
  name: Ionburst Cloud Status
  introTitle: "The low-effort, high-security platform for developers storing data in the cloud."
  introMessage: We continuously monitor Ionburst Cloud and its underlying services. If there are any performance issues or service interruptions, an update will be posted here.
  navbar:
    - title: Status
      href: /
    - title: Ionburst Cloud
      href: https://ionburst.cloud
  favicon: https://status.ionburst.cloud/favicon.png
  faviconSvg: https://status.ionburst.cloud/icon.svg
  scripts:
    - src: https://plausible.io/js/plausible.js
      defer: true
      data-domain: status.ionburst.cloud

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

commitMessages:
  commitAuthorName: "Ionbot"
  commitAuthorEmail: "ionbot@ionburst.cloud"
user-agent: ionbot-ibc